version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/staticfiles:/home/app/web/staticfiles
      - ./app/meadiafiles:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
    networks:
      - main


  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - main



  nginx:
    build: ./nginx
    volumes:
      - ./app/staticfiles:/staticfiles
      - ./app/mediafiles:/mediafiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - main

  
  bot:
    build: ./tg_bot
    command: python tg_vulpers.py
    volumes:
      - ./tg_bot/:/usr/src/app/
    env_file:
      - ./tg_bot/prod.env
    networks:
      - main


volumes:
  postgres_data:

