version: "3"
services:

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - main
    ports:
      - 5434:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    depends_on:
      - "postgres"
    networks:
      - main
    restart: unless-stopped

  web:
    build: ./web
    command: gunicorn --workers=3 --bind=0.0.0.0:8000 run:app
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 80:8000
    env_file:
      - ./web/dev.env
    networks:
      - main

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - /etc/ssl/:/etc/ssl/
    depends_on:
      - web
    networks:
      - main
    

volumes:
  pg-data:
  pgadmin:

networks:
  main:
    driver: bridge