"""empty message

Revision ID: c1a356d63ce4
Revises: b0d99ef3e190
Create Date: 2023-01-30 16:08:47.431111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a356d63ce4'
down_revision = 'b0d99ef3e190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_pay', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('is_pay')
        batch_op.drop_column('is_confirm')

    # ### end Alembic commands ###
